// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );ff
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOGxonuJMR4-Ozs3yvM2i98Rg9De459dY',
    appId: '1:608227332602:web:aa70a4ccc34a51f068d443',
    messagingSenderId: '608227332602',
    projectId: 'fir-crud-44ad9',
    authDomain: 'fir-crud-44ad9.firebaseapp.com',
    storageBucket: 'fir-crud-44ad9.appspot.com',
    measurementId: 'G-ZPK3NNFXXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-avBRMFNBPr49fi3XadMTkKhQ0flpCs',
    appId: '1:608227332602:android:722cb064035c265868d443',
    messagingSenderId: '608227332602',
    projectId: 'fir-crud-44ad9',
    storageBucket: 'fir-crud-44ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_hANoBL-_CQimp-sPL-p38b5XeMyvfgE',
    appId: '1:608227332602:ios:e3e85da333c5f33268d443',
    messagingSenderId: '608227332602',
    projectId: 'fir-crud-44ad9',
    storageBucket: 'fir-crud-44ad9.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_hANoBL-_CQimp-sPL-p38b5XeMyvfgE',
    appId: '1:608227332602:ios:e3e85da333c5f33268d443',
    messagingSenderId: '608227332602',
    projectId: 'fir-crud-44ad9',
    storageBucket: 'fir-crud-44ad9.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOGxonuJMR4-Ozs3yvM2i98Rg9De459dY',
    appId: '1:608227332602:web:62fec45392a4dca768d443',
    messagingSenderId: '608227332602',
    projectId: 'fir-crud-44ad9',
    authDomain: 'fir-crud-44ad9.firebaseapp.com',
    storageBucket: 'fir-crud-44ad9.appspot.com',
    measurementId: 'G-LS794J3FLH',
  );
}
